name: Node.js CI
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: "Build"
        run: |
          npm install
          npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.API_WEATHER_BASE_URL }}
          VITE_APPID: ${{ secrets.API_WEATHER_ID }}

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ github.token }}
